I update the contributing docs more detailed and easy understand
horuslabsio/Starknet-Scaffold pull request #93
Opened 2024-05-29 13:08 UTC by mimiprosper

## Description

Contributing to Starknet Scaffold.

I update the contributing docs for Starknet Scaffold for more detailed and easy understand

## Related Issues

Closes #82

2024-05-30 12:35 UTC, Darlington02 requested changes
Please rewrite the whole thing. You are writing a guide for the Starknet Scaffold project built on Starknet not scaffold-eth-2.

Just simply copy what we already have here, with some minimal updates as you see fit:
https://github.com/argentlabs/Starknet-Scaffold/blob/main/CONTRIBUTING.md

2024-05-30 12:35 UTC, Darlington02 commented on docs/src/chapter_8.md
> +Welcome to the Scaffold-ETH 2 contributing guide! Thank you for investing your time in contributing to our project. This guide aims to provide a comprehensive overview of the contribution workflow, e
Starknet-Scaffold not Scaffold-ETH2

2024-05-30 12:35 UTC, Darlington02 commented on docs/src/chapter_8.md
> +Scaffold-ETH 2 is a minimal and forkable repository providing builders with a starter kit to develop decentralized applications (dApps) on Ethereum. For an overview of the project, please read the [R
Starknet Scaffold!

2024-05-30 12:37 UTC, Darlington02 commented on docs/src/chapter_8.md
> +Scaffold-ETH 2 is a minimal and forkable repository providing builders with a starter kit to develop decentralized applications (dApps) on Ethereum. For an overview of the project, please read the [R
and don't close the issue from your PR, leave the Related issue empty

2024-05-30 12:47 UTC, mimiprosper commented
Goodmorning Boss,

I have taken note of the instruction. I would  fix them right away.

Thanks.

2024-05-31 07:59 UTC, mimiprosper commented
Contributing to Starknet Scaffold.

I have made the correction and updates.

Related Issue #82

2024-05-31 09:07 UTC, mimiprosper commented
I have update my comments so that i don't mention the issue

2024-05-31 09:21 UTC, merged

2024-05-31 09:22 UTC, Darlington02 commented
> Contributing to Starknet Scaffold.
> 
> I have made the correction and updates.

Ty ser! merged